import {Dimensions, Platform, StyleSheet} from 'react-native';

const width = Dimensions.get('window').width;
export default StyleSheet.create({
  card: {
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    padding: 50,
    height: 500,
    width: width,
    marginTop: 300,
    marginLeft: 30,
  },
  image: {
    height: 250,
    width: width,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: 'black',
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'right',
    bottom: 50,
    right: 0,
    paddingBottom: 24,
    paddingRight: 5,
    marginLeft: 30,
    position: 'absolute',
  },
  writer: {
    bottom: 0,
    right: 0,
    position: 'absolute',
    color: '#a0a0a0',
    fontSize: 20,
    padding: 5,
  },
  section: {
    color: 'white',
    fontSize: Platform.OS === 'ios' ? 10 : 8,
    fontWeight: 'bold',
    textAlign: 'right',
    position: 'absolute',
    right: 5,
    top: 120,
    paddingBottom: 2,
    paddingRight: 8,
    backgroundColor: 'black',
    height: 25,
    width: 57,
  },
});
