import {Dimensions, Platform, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const width = Dimensions.get('window').width;
export default StyleSheet.create({
  card: {
    width: Platform.OS === 'ios' ? wp('100%') : wp('105%'),
    height: 520,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.03)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 4,
    shadowOpacity: 1,
    flex: 1,
    alignItems: 'center',
    marginBottom: 10,
  },
  image: {width: 400, height: 435},
  writer: {
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'right',
    color: '#02f784',
  },

  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
    marginBottom: 5,
    width: wp('38%'),
    alignItems: 'center',
  },
  time: {
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 30,
    letterSpacing: 0,
    color: '#cdcdcd',
    marginRight: 20,
  },
  col: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: hp('43%'),
  },
  magazine: {
    justifyContent: 'center',
    width: 56,
    height: Platform.OS === 'ios' ? 21 : 30,
    fontSize: 21,
    fontWeight: '900',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#141414',
    alignSelf: 'center',
  },
  rectangle: {
    width: 74,
    height: 26,
    backgroundColor: '#02f784',
    justifyContent: 'center',
  },
  title: {
    width: 350,
    height: 56,
    fontSize: 27,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 28,
    letterSpacing: 0.5,
    textAlign: 'center',
    color: '#ffffff',
    marginTop: 18,
  },
  line: {
    width: 344,
    height: 1,
    opacity: 0.19,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#979797',
  },
  link: {
    width: wp('50%'),
    height: 50,
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#d9d9d9',
    marginTop: 30,
    justifyContent: 'center',
    alignContent: 'center',
  },
  blackRec: {
    width: Platform.OS === 'ios' ? 400 : wp('93%'),
    height: hp('10%'),
    borderRadius: 5,
    backgroundColor: '#141514',
    shadowColor: 'rgba(0, 0, 0, 0.03)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 4,
    shadowOpacity: 1,
    alignItems: 'center',
    padding: 5,
  },
});
