import {Dimensions, Platform, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const width = Dimensions.get('window').width;
export default StyleSheet.create({
  card: {
    width: Platform.OS === 'ios' ? wp('100%') : wp('105%'),
    height: 408,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.03)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 4,
    shadowOpacity: 1,
    flex: 1,
    alignItems: 'center',
    marginBottom: 10,
  },
  purpleCard: {
    backgroundColor: '#4a134a',
    width: Platform.OS === 'ios' ? wp('100%') : wp('105%'),
    height: 204,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    position: 'absolute',
  },
  title: {
    fontSize: 22,
    width: wp('90%'),
    fontWeight: '600',
    fontStyle: 'normal',
    textAlign: 'right',
    color: '#f2f2f2',
    marginRight: 5,
    marginTop: Platform.OS === 'ios' ? 13 : 7,
  },
  subTitle: {
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    justifyContent: 'flex-start',
    color: '#e4e4e4',
    right: 90,
    top: 15,
  },
  image: {
    width: 25,
    height: 25,
    marginTop: 10,
    marginRight: Platform.OS === 'ios' ? 10 : 30,
  },
  grayCard: {
    backgroundColor: '#e4e4e4',
    width: Platform.OS === 'ios' ? wp('100%') : wp('105%'),
    height: 255,
    position: 'relative',
    bottom: 175,
    zIndex: -1,
  },
  listImage: {
    width: wp('60%'),
    padding: 10,
    height: 280,
    paddingTop: 100,
    paddingRight: 5,
    borderRadius: 10,
  },
  text: {
    width: 150,
    height: 50,
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 19,
    letterSpacing: 0,
    textAlign: 'right',
    color: '#e9e9e9',
    marginTop: 120,
    padding: 2,
    marginLeft: 60,
  },
  flatContainer: {
    height: 280,
    width: width,
    justifyContent: 'space-between',
    position: 'relative',
    marginTop: 85,
  },
  item: {
    marginLeft: 30,
    shadowOpacity: 2,
  },
});
